apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  lables:
    app.flask.server: service
spec:
  selector:
    app.flask.server: node
  ports:
    - protocol: TCP
      port: 2222 # service
      targetPort: 8080 # pod
  type: LoadBalancer
